### ISSUE TITLE
src files not getting deleted in build

### ISSUE THREAD

**Issue by cameronjroe** [christophercliff/metalsmith-webpack#11]
When I run a build the src js files get copied to the build folder.. shouldn't they be deleted during the build process?

**Comment by cameronjroe** [comment]
?

**Comment by 1Copenut** [comment]
Bumping this as I'm seeing the same issue. I'm able to create the /build/js folder, and the outputted file, but was a bit surprised to see the source file(s) included there.

**Comment by christophercliff** [comment]
More discussion in the threads linked here: https://github.com/metalsmith/metalsmith/issues/145.

tldr; this is probably a "wontfix".

**Comment by 1Copenut** [comment]
@christophercliff That thread sealed it, thank you.
